#!/bin/bash

OPT=$1

DEFAULT='\e[0m'
BOLD='\e[1m'
RED='\e[91m'
GREEN='\e[32m'
BLUE='\e[34m'

if [ "$OPT" == "--prod" ]; then
    ng build --prod
    echo -e "${RED}Production${DEFAULT} build attempt finished"
elif [ "$OPT" == "--watch" ]; then
    ng build --watch
    echo -e "${RED}Production${DEFAULT} watching..."
else
    ng build
    echo -e "${GREEN}Development${DEFAULT} build attempt finished. Add ${BOLD}--prod ${DEFAULT}for production build"
fi
